name: Run release-please

on:
  workflow_dispatch:
    inputs:
      component-name:
        description: Component name (workflow name without .yml extension, or action name).
        required: true
        type: string
      component-type:
        description: Type of component to release.
        required: true
        type: choice
        default: action
        options:
          - workflow
          - action
      config-json-path:
        description: Path to the release-please config JSON file (relative to repo root).
        required: true
        default: .github/release-please/actions-config.json
        type: string
      manifest-json-path:
        description: Path to the release-please manifest JSON file (relative to repo root).
        required: true
        default: .github/release-please/actions-manifest.json
        type: string

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  check-workflow-config:

    if: inputs.component-type == 'workflow'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7

      - name: Check workflow config is up to date
        run: |
          .github/release-please-script/check-workflow-config-uptodate.sh \
            --workflow "${{ inputs.component-name }}"

  run-release-please:
    needs: check-workflow-config
    if: always() && (needs.check-workflow-config.result == 'success' || needs.check-workflow-config.result == 'skipped')
    runs-on: ubuntu-latest
    steps:
      # ATTENTION: If the changelog file is within the .github/workflows folder, then this workflow needs some special permissions (workflow)
      # since Github assumes only workflow files are in this folder. Unfortunately these permissions cannot be given by the "permissions" block
      # in above YAML, but need to be provided to a PAT and then this PAT must be handed over to this workflow and then used by release-please.
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 #v5
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN || github.token }}
          config-file: ${{ inputs.config-json-path }}
          manifest-file: ${{ inputs.manifest-json-path }}
